# Generated by Django 3.1.7 on 2021-06-11 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Nom', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Post_Nom', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Prenom', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Numero', models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='N°')),
                ('Rue', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Quartier', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Commune', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Ville', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Province', models.CharField(blank=True, choices=[('Bas-Uele', 'Bas-Uele'), ('Équateur', 'Équateur'), ('Haut-Katanga', 'Haut-Katanga'), ('Haut-Lomami', 'Haut-Lomami'), ('Haut-Uele', 'Haut-Uele'), ('Ituri', 'Ituri'), ('Kasaï', 'Kasaï'), ('Kasaï-Central', 'Kasaï-Central'), ('Kasaï oriental', 'Kasaï oriental'), ('Kinshasa', 'Kinshasa'), ('Kongo central', 'Kongo central'), ('Kwango', 'Kwango'), ('Kwilu', 'Kwilu'), ('Lomami', 'Lomami'), ('Lualaba', 'Lualaba'), ('Mai-Ndombe', 'Mai-Ndombe'), ('Maniema', 'Maniema'), ('Mongala', 'Mongala'), ('Nord-Kivu', 'Nord-Kivu'), ('Nord-Ubangi', 'Nord-Ubangi'), ('Sankuru', 'Sankuru'), ('Sud-Kivu', 'Sud-Kivu'), ('Sud-Ubangi', 'Sud-Ubangi'), ('Tanganyika', 'Tanganyika'), ('Tshopo', 'Tshopo'), ('Tshuapa', 'Tshuapa')], default='-', max_length=20, null=True)),
                ('Tel1', models.CharField(blank=True, default='-', max_length=13, null=True, verbose_name='Téléphone 1')),
                ('Tel2', models.CharField(blank=True, default='-', max_length=13, null=True, verbose_name='Téléphone 2')),
                ('Tel3', models.CharField(blank=True, default='-', max_length=13, null=True, verbose_name='Téléphone 3')),
                ('Email', models.EmailField(blank=True, default='contact@advans.com', max_length=254, null=True)),
                ('Website', models.URLField(blank=True, default='-', null=True, verbose_name='Site Web')),
                ('Facebook', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Instagram', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Twitter', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('LinkedIn', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Remarque', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
