# Generated by Django 3.1.7 on 2021-07-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Tel1',
            new_name='phonenumber',
        ),
    ]
