# Generated by Django 3.1.7 on 2021-04-23 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('questons1', models.BooleanField(null=True)),
                ('questons2', models.BooleanField(null=True)),
                ('questons3', models.BooleanField(null=True)),
                ('questons4', models.BooleanField(null=True)),
                ('questons5', models.BooleanField(null=True)),
                ('questons6', models.BooleanField(null=True)),
                ('questons7', models.BooleanField(null=True)),
                ('questons8', models.BooleanField(null=True)),
                ('questons9', models.BooleanField(null=True)),
                ('questons10', models.BooleanField(null=True)),
                ('questons11', models.BooleanField(null=True)),
                ('questons12', models.BooleanField(null=True)),
                ('questons13', models.BooleanField(null=True)),
                ('questons14', models.BooleanField(null=True)),
                ('questons15', models.BooleanField(null=True)),
                ('questons16', models.BooleanField(null=True)),
                ('questons17', models.BooleanField(null=True)),
                ('questons18', models.BooleanField(null=True)),
                ('questons19', models.BooleanField(null=True)),
                ('montant_de_prêt', models.CharField(blank=True, max_length=100, null=True)),
                ('durée_de_crédit', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_a_rembourser_chaque_mois', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_des_ventes_bonne_journée', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_des_ventes_mauvaise_journée', models.CharField(blank=True, max_length=100, null=True)),
                ('date_a_laquelle_recevoir_credit', models.CharField(blank=True, max_length=100, null=True)),
                ('Nom_du_garant', models.CharField(blank=True, max_length=100, null=True)),
                ('Activite', models.CharField(blank=True, max_length=100, null=True)),
                ('Nom_societe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la société')),
                ('Nom', models.CharField(blank=True, max_length=100, null=True)),
                ('Post_Nom', models.CharField(blank=True, max_length=100, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('Numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='N°')),
                ('Quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('Commune', models.CharField(blank=True, max_length=100, null=True)),
                ('Province', models.CharField(blank=True, choices=[('Bas-Uele', 'Bas-Uele'), ('Équateur', 'Équateur'), ('Haut-Katanga', 'Haut-Katanga'), ('Haut-Lomami', 'Haut-Lomami'), ('Haut-Uele', 'Haut-Uele'), ('Ituri', 'Ituri'), ('Kasaï', 'Kasaï'), ('Kasaï-Central', 'Kasaï-Central'), ('Kasaï oriental', 'Kasaï oriental'), ('Kinshasa', 'Kinshasa'), ('Kongo central1', 'Kongo central1'), ('Kwango', 'Kwango'), ('Kwilu', 'Kwilu'), ('Lomami', 'Lomami'), ('Lualaba', 'Lualaba'), ('Mai-Ndombe', 'Mai-Ndombe'), ('Maniema', 'Maniema'), ('Mongala', 'Mongala'), ('Nord-Kivu', 'Nord-Kivu'), ('Nord-Ubangi', 'Nord-Ubangi'), ('Sankuru', 'Sankuru'), ('Sud-Kivu', 'Sud-Kivu'), ('Sud-Ubangi', 'Sud-Ubangi'), ('Tanganyika', 'Tanganyika'), ('Tshopo', 'Tshopo'), ('Tshuapa', 'Tshuapa')], max_length=20, null=True)),
                ('Pays', models.CharField(blank=True, choices=[('Afrique du Sud', 'Afrique du Sud'), ('Afghanistan', 'Afghanistan'), ('Albanie', 'Albanie'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Andorre', 'Andorre'), ('Angola', 'Angola'), ('Antigua-et-Barbuda', 'Antigua-et-Barbuda'), ('Arabie Saoudite', 'Arabie Saoudite'), ('Argentine', 'Argentine'), ('Arménie', 'Arménie'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Azerbaïdjan', 'Azerbaïdjan'), ('Bahamas', 'Bahamas'), ('Bahreïn', 'Bahreïn'), ('Bangladesh', 'Bangladesh'), ('Barbade', 'Barbade'), ('Belgique', 'Belgique'), ('Belize', 'Belize'), ('Bénin', 'Bénin'), ('Bhoutan', 'Bhoutan'), ('Biélorussie', 'Biélorussie'), ('Birmanie', 'Birmanie'), ('Bolivie', 'Bolivie'), ('Bosnie-Herzégovine', 'Bosnie-Herzégovine'), ('Botswana', 'Botswana'), ('Brésil', 'Brésil'), ('Brunei', 'Brunei'), ('Bulgarie', 'Bulgarie'), ('Burkina ,', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cambodge', 'Cambodge'), ('Cameroun', 'Cameroun'), ('Canada', 'Canada'), ('Cap-Vert', 'Cap-Vert'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Chypre', 'Chypre'), ('Colombie', 'Colombie'), ('Comores', 'Comores'), ('Corée du Nord', 'Corée du Nord'), ('Corée du Sud', 'Corée du Sud'), ('Costa Rica', 'Costa Rica'), ('Côte d’Ivoire', 'Côte d’Ivoire'), ('Croatie', 'Croatie'), ('Cuba', 'Cuba'), ('Danemark', 'Danemark'), ('Djibouti', 'Djibouti'), ('Dominique', 'Dominique'), ('Égypte', 'Égypte'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Équateur', 'Équateur'), ('Érythrée', 'Érythrée'), ('Espagne', 'Espagne'), ('Eswatini', 'Eswatini'), ('Estonie', 'Estonie'), ('États-Unis', 'États-Unis'), ('Éthiopie', 'Éthiopie'), ('Fidji', 'Fidji'), ('Finlande', 'Finlande'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Géorgie', 'Géorgie'), ('Ghana', 'Ghana'), ('Grèce', 'Grèce'), ('Grenade', 'Grenade'), ('Guatemala', 'Guatemala'), ('Guinée', 'Guinée'), ('Guinée équatoriale', 'Guinée équatoriale'), ('Guinée-Bissau', 'Guinée-Bissau'), ('Guyana', 'Guyana'), ('Haïti', 'Haïti'), ('Honduras', 'Honduras'), ('Hongrie', 'Hongrie'), ('Îles Cook', 'Îles Cook'), ('Îles Marshall', 'Îles Marshall'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ('Irak', 'Irak'), ('Iran', 'Iran'), ('Irlande', 'Irlande'), ('Islande', 'Islande'), ('Israël', 'Israël'), ('Italie', 'Italie'), ('Jamaïque', 'Jamaïque'), ('Japon', 'Japon'), ('Jordanie', 'Jordanie'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kirghizistan', 'Kirghizistan'), ('Kiribati', 'Kiribati'), ('Koweït', 'Koweït'), ('Laos', 'Laos'), ('Lesotho', 'Lesotho'), ('Lettonie', 'Lettonie'), ('Liban', 'Liban'), ('Liberia', 'Liberia'), ('Libye', 'Libye'), ('Liechtenstein', 'Liechtenstein'), ('Lituanie', 'Lituanie'), ('Luxembourg', 'Luxembourg'), ('Macédoine', 'Macédoine'), ('Madagascar', 'Madagascar'), ('Malaisie', 'Malaisie'), ('Malawi', 'Malawi'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malte', 'Malte'), ('Maroc', 'Maroc'), ('Maurice', 'Maurice'), ('Mauritanie', 'Mauritanie'), ('Mexique', 'Mexique'), ('Micronésie', 'Micronésie'), ('Moldavie', 'Moldavie'), ('Monaco', 'Monaco'), ('Mongolie', 'Mongolie'), ('Monténégro', 'Monténégro'), ('Mozambique', 'Mozambique'), ('Namibie', 'Namibie'), ('Nauru', 'Nauru'), ('Népal', 'Népal'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Norvège', 'Norvège'), ('Nouvelle-Zélande', 'Nouvelle-Zélande'), ('Oman', 'Oman'), ('Ouganda', 'Ouganda'), ('Ouzbékistan', 'Ouzbékistan'), ('Pakistan', 'Pakistan'), ('Palaos', 'Palaos'), ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papouasie-Nouvelle-Guinée', 'Papouasie-Nouvelle-Guinée'), ('Paraguay', 'Paraguay'), ('Pays-Bas', 'Pays-Bas'), ('Pérou', 'Pérou'), ('Philippines', 'Philippines'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('République centrafricaine', 'République centrafricaine'), ('République démocratique du Congo', 'République démocratique du Congo'), ('République Dominicaine', 'République Dominicaine'), ('République du Congo', 'République du Congo'), ('République tchèque', 'République tchèque'), ('Roumanie', 'Roumanie'), ('Royaume-Uni', 'Royaume-Uni'), ('Russie', 'Russie'), ('Rwanda', 'Rwanda'), ('Saint-Kitts-et-Nevis', 'Saint-Kitts-et-Nevis'), ('Saint-Vincent-et-les-Grenadines', 'Saint-Vincent-et-les-Grenadines'), ('Sainte-Lucie', 'Sainte-Lucie'), ('Saint-Marin', 'Saint-Marin'), ('Salomon', 'Salomon'), ('Salvador', 'Salvador'), ('Samoa', 'Samoa'), ('São Tomé-et-Principe', 'São Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Serbie', 'Serbie'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapour', 'Singapour'), ('Slovaquie', 'Slovaquie'), ('Slovénie', 'Slovénie'), ('Somalie', 'Somalie'), ('Soudan', 'Soudan'), ('Soudan du Sud', 'Soudan du Sud'), ('Sri Lanka', 'Sri Lanka'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Suriname', 'Suriname'), ('Syrie', 'Syrie'), ('Tadjikistan', 'Tadjikistan'), ('Tanzanie', 'Tanzanie'), ('Tchad', 'Tchad'), ('Thaïlande', 'Thaïlande'), ('Timor oriental', 'Timor oriental'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinité-et-Tobago', 'Trinité-et-Tobago'), ('Tunisie', 'Tunisie'), ('Turkménistan', 'Turkménistan'), ('Turquie', 'Turquie'), ('Tuvalu', 'Tuvalu'), ('Ukraine', 'Ukraine'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu'), ('Vatican', 'Vatican'), ('Venezuela', 'Venezuela'), ('Viêt Nam', 'Viêt Nam'), ('Yémen', 'Yémen'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')], max_length=100, null=True)),
                ('Tel1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Téléphone 1')),
                ('Tel2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Téléphone 2')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Website', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('Facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('LinkedIn', models.CharField(blank=True, max_length=100, null=True)),
                ('Statut', models.CharField(blank=True, choices=[('Statuts de reporting', 'Statuts de reporting'), ('Accord', 'Accord'), ('Déjà payé son crédit', 'Déjà payé son crédit'), ('Refus', 'Refus'), ('Rappel', 'Rappel (interlocuteur demande de rappeler)'), ('Injoignable', 'Injoignable'), ('Absent', 'Absent'), ('Faux numéro', 'Faux numéro'), ('Réfléchir', 'Réfléchir')], max_length=30, null=True)),
                ('Remarque', models.TextField()),
                ('Commentaire', models.TextField()),
                ('Concurrent', models.CharField(blank=True, choices=[('Statuts de reporting', 'Statuts de reporting'), ('Accord', 'Accord'), ('Déjà payé son crédit', 'Déjà payé son crédit'), ('Refus', 'Refus'), ('Rappel', 'Rappel (interlocuteur demande de rappeler)'), ('Injoignable', 'Injoignable'), ('Absent', 'Absent'), ('Faux numéro', 'Faux numéro'), ('Réfléchir', 'Réfléchir')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
