# Generated by Django 3.1.7 on 2021-04-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210423_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='questons14',
            new_name='Q19temps_a_contacter',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='questons17',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='questons18',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='questons19',
        ),
    ]
