# Generated by Django 3.1.7 on 2021-04-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210423_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='durée_de_crédit',
            new_name='duree_de_credit',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='montant_de_prêt',
            new_name='montant_de_pret',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='montant_des_ventes_bonne_journée',
            new_name='montant_des_ventes_bonne_journee',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='montant_des_ventes_mauvaise_journée',
            new_name='montant_des_ventes_mauvaise_journee',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='questons11',
        ),
    ]
