# Generated by Django 3.1.7 on 2021-05-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20210503_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acquisition',
        ),
        migrations.DeleteModel(
            name='CommercialePromotion',
        ),
        migrations.DeleteModel(
            name='CompteDormant',
        ),
        migrations.DeleteModel(
            name='Recouvrement',
        ),
    ]
