# Generated by Django 3.1.7 on 2021-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210424_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='questons1',
            new_name='questions1',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons10',
            new_name='questions10',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons12',
            new_name='questions12',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons13',
            new_name='questions13',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons15',
            new_name='questions15',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons16',
            new_name='questions16',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons2',
            new_name='questions2',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons3',
            new_name='questions3',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons4',
            new_name='questions4',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons5',
            new_name='questions5',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons6',
            new_name='questions6',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons7',
            new_name='questions7',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons8',
            new_name='questions8',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='questons9',
            new_name='questions9',
        ),
    ]
