# Generated by Django 3.1.7 on 2021-05-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210504_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Pays',
        ),
        migrations.AddField(
            model_name='contact',
            name='Rue',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ville',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
