# Generated by Django 3.1.7 on 2021-05-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210506_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
