# Generated by Django 3.1.7 on 2021-04-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Remarque',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
