# Generated by Django 3.1.7 on 2021-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0003_auto_20210502_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat',
            name='Statut',
            field=models.CharField(choices=[('Statuts de reporting', 'Statuts de reporting'), ('Accord', 'Accord'), ('Déjà payé son crédit', 'Déjà payé son crédit'), ('Refus', 'Refus'), ('Rappel', 'Rappel (interlocuteur demande de rappeler)'), ('Injoignable', 'Injoignable'), ('Absent', 'Absent'), ('Faux numéro', 'Faux numéro'), ('Réfléchir', 'Réfléchir')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dat',
            name='questions1',
            field=models.CharField(default='NON', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dat',
            name='questions2',
            field=models.CharField(default='NON', max_length=200, null=True),
        ),
    ]
