# Generated by Django 3.1.7 on 2021-05-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0004_auto_20210502_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat',
            name='Email',
            field=models.EmailField(blank=True, default='contact@advans.com', max_length=254, null=True),
        ),
    ]
