# Generated by Django 3.1.7 on 2021-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0005_auto_20210503_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat',
            name='questions1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dat',
            name='questions2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
