# Generated by Django 3.1.7 on 2021-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0007_auto_20210503_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat',
            name='questions1',
            field=models.CharField(default='NON', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dat',
            name='questions2',
            field=models.CharField(default='NON', max_length=200, null=True),
        ),
    ]
