# Generated by Django 3.1.7 on 2021-05-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0009_auto_20210503_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat',
            name='Remarque',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
