# Generated by Django 3.1.7 on 2021-05-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0011_auto_20210504_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dat',
            old_name='questions1',
            new_name='questons1',
        ),
        migrations.RenameField(
            model_name='dat',
            old_name='questions2',
            new_name='questons2',
        ),
    ]
