# Generated by Django 3.1.7 on 2021-05-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0012_auto_20210504_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dat',
            old_name='questons1',
            new_name='questions1',
        ),
        migrations.RenameField(
            model_name='dat',
            old_name='questons2',
            new_name='questions2',
        ),
    ]
