# Generated by Django 3.1.7 on 2021-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0013_auto_20210504_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat',
            name='Rue',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dat',
            name='Ville',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
