# Generated by Django 3.1.7 on 2021-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('dat', '0014_auto_20210506_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dat',
            name='Commune',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Post_Nom',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Prenom',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Quartier',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Remarque',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Rue',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Tel1',
        ),
        migrations.RemoveField(
            model_name='dat',
            name='Ville',
        ),
        migrations.AddField(
            model_name='dat',
            name='Contact',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
