# Generated by Django 3.1.7 on 2021-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='Remarque',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
