# Generated by Django 3.1.7 on 2021-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0002_auto_20210504_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouvrement',
            name='Rue',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='Ville',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
