# Generated by Django 3.1.7 on 2021-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commprom', '0002_auto_20210503_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='commprom',
            name='Remarque',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
