# Generated by Django 3.1.7 on 2021-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commprom', '0003_commprom_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commprom',
            name='Email',
            field=models.EmailField(blank=True, default='contact@advans.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commprom',
            name='questions1',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commprom',
            name='questions2',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
