# Generated by Django 3.1.7 on 2021-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptedormant', '0002_auto_20210505_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte_dormant',
            name='Raison',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
