# Generated by Django 3.1.7 on 2021-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur')], max_length=100, null=True),
        ),
    ]
