# Generated by Django 3.1.7 on 2021-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/images/avatar.jpg', upload_to='user-profile/'),
        ),
    ]
