# Generated by Django 3.1.7 on 2021-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210516_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='avatar.jpg', upload_to='user-profile/'),
        ),
    ]
