# Generated by Django 3.1.7 on 2021-04-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210406_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Agent', 'Agent'), ('Client', 'Client')], max_length=100, null=True),
        ),
    ]
