# Generated by Django 3.1.7 on 2021-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210415_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/user-bg.jpg', upload_to='user-profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], max_length=100, null=True),
        ),
    ]
