# Generated by Django 3.1.7 on 2021-04-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210424_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experiance',
            new_name='experience',
        ),
    ]
