# Generated by Django 3.1.7 on 2021-04-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210424_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
