# Generated by Django 3.1.7 on 2021-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0002_auto_20210508_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip_conf',
            name='amaflags',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default='billing', help_text='indicateurs spéciaux pour contrôler le calcul par défaut', max_length=20, null=True),
        ),
    ]
