# Generated by Django 3.1.7 on 2021-06-11 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renouvellement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('questions1', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions2', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions3', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions4', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions5', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions6', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions7', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions8', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions9', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions10', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions12', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions13', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions15', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('questions16', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('Q19temps_a_contacter', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('montant_de_pret', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('duree_de_credit', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('montant_a_rembourser_chaque_mois', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('montant_des_ventes_bonne_journee', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('montant_des_ventes_mauvaise_journee', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('date_a_laquelle_recevoir_credit', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Nom_du_garant', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Activite', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Statut', models.CharField(blank=True, choices=[('---------', '--------------'), ('Accord', 'Accord'), ('Déjà payé son crédit', 'Déjà payé son crédit'), ('Refus', 'Refus'), ('Rappel', 'Rappel (interlocuteur demande de rappeler)'), ('Injoignable', 'Injoignable'), ('Absent', 'Absent'), ('Faux numéro', 'Faux numéro'), ('Réfléchir', 'Réfléchir')], default='-', max_length=30, null=True)),
                ('Commentaire', models.TextField(blank=True, default='-', null=True)),
                ('Concurrent', models.TextField(blank=True, default='-', null=True)),
                ('CommentaireQ17', models.TextField(blank=True, default='-', null=True)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
