# Generated by Django 3.1.7 on 2021-05-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renouvellement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renouvellement',
            old_name='Facebook',
            new_name='Rue',
        ),
        migrations.RenameField(
            model_name='renouvellement',
            old_name='Instagram',
            new_name='Ville',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='LinkedIn',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='Pays',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='Tel2',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='Twitter',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='Website',
        ),
    ]
