# Generated by Django 3.1.7 on 2021-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('uniqueid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('calldate', models.DateTimeField()),
                ('clid', models.CharField(blank=True, max_length=80)),
                ('src', models.CharField(blank=True, max_length=80)),
                ('dst', models.CharField(blank=True, max_length=80)),
                ('dcontext', models.CharField(blank=True, max_length=80)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('dstchannel', models.CharField(blank=True, max_length=80)),
                ('lastapp', models.CharField(blank=True, max_length=80)),
                ('lastdata', models.CharField(blank=True, max_length=80)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('billsec', models.IntegerField(blank=True, default=0)),
                ('disposition', models.CharField(db_index=True, default='', max_length=45)),
                ('amaflags', models.PositiveIntegerField(db_index=True, default=0)),
                ('accountcode', models.CharField(blank=True, max_length=20)),
                ('userfield', models.CharField(blank=True, max_length=255)),
                ('recordingfile', models.CharField(blank=True, max_length=255)),
                ('cnum', models.CharField(blank=True, max_length=80)),
                ('cnam', models.CharField(blank=True, max_length=80)),
                ('outbound_cnum', models.CharField(blank=True, max_length=80)),
                ('outbound_cnam', models.CharField(blank=True, max_length=80)),
                ('dst_cnam', models.CharField(blank=True, max_length=80)),
                ('did', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'cdr',
            },
        ),
        migrations.CreateModel(
            name='Cel',
            fields=[
                ('uniqueid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('eventtime', models.DateTimeField(auto_now_add=True)),
                ('eventtype', models.CharField(blank=True, default='', max_length=80)),
                ('cid_name', models.CharField(blank=True, default='', max_length=80)),
                ('cid_num', models.CharField(blank=True, default='', max_length=80)),
                ('cid_ani', models.CharField(blank=True, default='', max_length=80)),
                ('cid_rdnis', models.CharField(blank=True, default='', max_length=80)),
                ('cid_dnid', models.CharField(blank=True, default='', max_length=80)),
                ('exten', models.CharField(blank=True, default='', max_length=80)),
                ('context', models.CharField(blank=True, default='', max_length=80)),
                ('channame', models.CharField(blank=True, default='', max_length=80)),
                ('appname', models.CharField(blank=True, default='', max_length=80)),
                ('appdata', models.CharField(blank=True, default='', max_length=80)),
                ('amaflags', models.IntegerField(blank=True, default=0)),
                ('accountcode', models.CharField(blank=True, default='', max_length=20)),
                ('linkedid', models.CharField(blank=True, default='', max_length=80)),
                ('peer', models.CharField(blank=True, default='', max_length=80)),
                ('userdeftype', models.CharField(blank=True, default='', max_length=255)),
                ('eventextra', models.CharField(blank=True, default='', max_length=255)),
                ('userfield', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'cel',
            },
        ),
    ]
