# Generated by Django 3.1.7 on 2021-06-11 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('questions1', models.CharField(default='-', max_length=200, null=True)),
                ('questions3', models.CharField(choices=[('Crédit', 'Crédit'), ('Comptes/épargne', 'Comptes/épargne'), ('Les deux', 'Les deux'), ('Autres', 'Autres')], default='-', max_length=200, null=True)),
                ('questions4', models.CharField(default='-', max_length=200, null=True)),
                ('questions5', models.CharField(default='-', max_length=200, null=True)),
                ('questions6', models.CharField(default='-', max_length=200, null=True)),
                ('Statut', models.CharField(choices=[('---------', '--------------'), ('Accord', 'Accord'), ('Déjà payé son crédit', 'Déjà payé son crédit'), ('Refus', 'Refus'), ('Rappel', 'Rappel (interlocuteur demande de rappeler)'), ('Injoignable', 'Injoignable'), ('Absent', 'Absent'), ('Faux numéro', 'Faux numéro'), ('Réfléchir', 'Réfléchir')], max_length=30, null=True)),
                ('CommentaireQ5', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('CommentaireQ6', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
