

PROVINCES = (
    # ('--------', '--------'),
    ('Bas-Uele', 'Bas-Uele'),
    ('Équateur', 'Équateur'),
    ('Haut-Katanga', 'Haut-Katanga'),
    ("Haut-Lomami", "Haut-Lomami"),	
    ('Haut-Uele', 'Haut-Uele'),
    ('Ituri', 'Ituri'),
    ('Kasaï', 'Kasaï'),
    ('Kasaï-Central', 'Kasaï-Central'),
    ('Kasaï oriental', 'Kasaï oriental'),
    ('Kinshasa', 'Kinshasa'),
    ('Kongo central', 'Kongo central'),
    ('Kwango', 'Kwango'),
    ('Kwilu', 'Kwilu'),
    ('Lomami', 'Lomami'),
    ('Lualaba', 'Lualaba'),
    ('Mai-Ndombe', 'Mai-Ndombe'),
    ('Maniema', 'Maniema'),
    ('Mongala', 'Mongala'),
    ('Nord-Kivu', 'Nord-Kivu'),
    ('Nord-Ubangi', 'Nord-Ubangi'),
    ('Sankuru', 'Sankuru'),
    ('Sud-Kivu', 'Sud-Kivu'),
    ('Sud-Ubangi', 'Sud-Ubangi'),
    ('Tanganyika', 'Tanganyika'),
    ('Tshopo', 'Tshopo'),
    ('Tshuapa', 'Tshuapa'),
)
